project:
  type: book
  output-dir: docs

book:
  title: "PsychoPy Training"
  author: "Matt Green"
  date: last-modified
  date-format: "dddd D MMM YYYY [at] HH[:]mm[:]ss"
  toc-depth: 3

  chapters:
    - index.qmd
    - part: getting-started.qmd
      chapters:
        - the-interface.qmd
        - the-builder.qmd
        - hello-world.qmd
    - part: intermediate.qmd
      chapters: 
        - stroop.qmd
    - part: advanced.qmd
      chapters: 
        - feedback.qmd
        - saving-data.qmd
        - using-sound.qmd
        - using-images.qmd
        - randomising.qmd
        - conditional-branching.qmd
        - online.qmd
    
    #    - instructions-routine.qmd
    #     - trial-procedure.qmd
    #     - trial-sequence.qmd
    #     - stimulus-files.qmd
    #     - making-the-trial-loop.qmd
    #     - finessing-the-trial-loop.qmd
    #     - keyboard-handling.qmd
    #     
    #     

  # chapters:
  #   - index.qmd
  #   - part: part-one.qmd
  #     chapters:
  #       - instructions-routine.qmd
  #       - trial-procedure.qmd
  #       - trial-sequence.qmd
  #       - stimulus-files.qmd
  #       - making-the-trial-loop.qmd
  #       - finessing-the-trial-loop.qmd
  #       - keyboard-handling.qmd
  #       - feedback.qmd
  #       - saving-data.qmd
  #   - part: part-two.qmd
  #     chapters:
  #       - using-sound.qmd
  #       - using-images.qmd
  #       - randomising.qmd
  #       - conditional-branching.qmd
  #       - online.qmd
  # #  - references.qmd
  # #appendices:
  # #  - authoring-tools.qmd

# bibliography: 
#   references.bib

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, theme-dark.scss]
      
      
# editor: 
#   source
  
# title-block-banner: 
#   #true
#   false

# crossref:
#     fig-title: Screencast
#     fig-prefix: Screencast


